# WSMC Configuration

# Set the WebSocket Endpoint for Minecraft login and server status.
# If empty or not set, a client can join the game via ANY WebSocket Endpoint.
# Must start with /, case-sensitive.
# Example: /mc
wsmcEndpoint: ""

# Show debug logs in the console.
debug: true

# Dump raw WebSocket binary frames. Work only if `debug` is set to `true`.
dumpBytes: false
