name: WSMC
version: 0.7.0
main: wsmc.paper.PaperEntry
api-version: 1.20
description: Enable Websocket support for Minecraft Java.
authors: [rikka0w0,wty2019wty]
website: hhttps://github.com/rikka0w0/wsmc/
